INSERT INTO airdyna.AIR_CRAFT (`AC_NAME`, `AC_SERIALNUM`, `AC_AFHRS`, `AC_ENGHRS`, `AC_LANDINGCOUNT`, `AC_STARTCOUNT`, `AC_ENGNGCYCS`, `AC_NPCYCS`, `AC_FORMNUM`) VALUES ('9N-AEX', '1612', '9267.2', '7998.4', '19139', '10255', '11092.7', '10255.0', 'ADH 310 A');

--------------------------------------------------------------------------------------------------------------------------------

INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Main Rotor Blade', '355A11-0010-07', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Main Rotor Head Attachment Bolt', '350A37-1244-20', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Main Rotor Head Attachment Bolt', '350A37-1245-20', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Main Rotor Shaft', '350A37-1076-12', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('M/R. Swashplate Bearing', '704A33-651-158', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Upper Sleeves', '350A31-1831-07', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Lower Sleeves', '350A31-1831-06', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Inboard Thurst Bearings', '704A33-633-21151', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Starflex', '350A31-1917-00', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Thrust Bearing Bolts', '350A31-2067-20', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Horn Blade', '350A31-1877-02', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Epicyclic Assy.', '350A32-0100-04', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Bevel  Reduction Gear', '350A32-0300-05', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Transmission Oil Pump', '350A32-0400-00', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Hyd.Pump P.V. Belt', 'Poly-V597K4(704A33-6900-08)', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Front Servo', 'AC67246', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Lateral Servo', 'AC67244', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Lateral Servo', 'AC67244', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Servo Tail Rotor', 'AC67032', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Tail Gear Box', '35033-0200-05', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Bearing, T/R Spider', '704A33-651-210', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('TRDS Bearing', '704A33-651-181', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Tail Rotor Blades', '355A12-0040-14', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Starter Generator', '150SG122Q', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Portable Fire Extinguisher', 'H1-10AIR ', 1);
INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('Rear Section Rear Transmission', '350A34-0210-06', 1);



	
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('5081', 1);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('7195', 1);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('5505', 1);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('77783', 2);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('78217', 2);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('78531', 2);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('78544', 2);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('78547', 2);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('78553', 2);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('71950', 3);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('71963', 3);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('72043', 3);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('72045', 3);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('72059', 3);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('72164', 3);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M5489', 4);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('NR4857', 5);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M20298', 6);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M20192', 6);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M20328', 6);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M19619', 7);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M19938', 7);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M20522', 7);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('1935', 8);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('1886', 8);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('1923', 8);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M2886', 9);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('25473', 10);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('25478', 10);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('27421', 10);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('27774', 10);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('243322', 10);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('25074', 10);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M4293', 11);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M4754', 11);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M4767', 11);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M260', 12);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M1219', 13);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M1273', 14);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('N/A', 15);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('DA178', 16);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('MU077', 17);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('DK255', 19);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('NC077', 19);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M1648', 20);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('NR0614', 21);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('N/A', 22);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('16222', 23);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('10492XL2', 24);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('33362', 25);
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('M3373', 26);




INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('20000.00','H', 1);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('3000.00','H', 2);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('3000.00','H', 3);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('20000.00','H', 4);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('120000','L', 4);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('4800.00','H', 5);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('4000.00','H', 6);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('4000.00','H', 6);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('4000.00','H', 7);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('4000.00','H', 7);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('6400.00','H', 8);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('2400.00','H', 9);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('5000.00','H', 10);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('80000.00','H', 11);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('2000.00','H', 12);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('3500.00','H', 13);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('3500.00','H', 14);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('1800.00','H', 15);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('6','Y', 15);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('1800.00','H', 16);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('1800.00','H', 17);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('1800.00','H', 18);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('1800.00','H', 19);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('3000.00','H', 20);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('3000.00','H', 21);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('3600.00','H', 22);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('5','Y', 22);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('4000.00','H', 23);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('1600.00','H', 24);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('10','Y', 25);
INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('20000.00','H', 26);


INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('17854.8','H',1);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('17444.6','H',1);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('17658.8','H',1);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('3000','H',2);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('3000','H',3);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('20000','H',4);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('120000','H',4);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('4800','H',5);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('4000','H',6);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('4000','H',6);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('4000','H',7);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('4000','H',7);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('6400','H',8);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('2400','H',9);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('5000','H',10);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('76388.26','H',11);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('2000','H',12);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('3500','H',13);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('3500','H',14);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('1800','H',15);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('6','Y',15);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('1800','H',16);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('1800','H',17);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('1800','H',18);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('1800','H',19);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('705.67','H',20);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('705.67','H',21);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('3600.00','H',22);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('5','Y',22);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('4000','H',23);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('1600','H',24);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('10','Y',25);
INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('20000.00','H',26);


INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('6923.8','H',1);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8827.8','H',2);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8827.8','H',2);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8827.8','H',3);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('6411','H',4);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('13462','H',4);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('6411','H',5);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7571.3','H',6);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7951.7','H',6);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('6843.6','H',7);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7951.7','H',7);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('5006','H',8);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7951.7','H',9);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7716.1','H',10);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('3588','H',11);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7951.7','H',12);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8291.4','H',13);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8291.4','H',14);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8827.8','H',15);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7815.6','H',16);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8754.2','H',17);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8253.3','H',18);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8376.1','H',19);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8796.8','H',20);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8796.8','H',21);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7324.6','H',22);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('8498.8','H',23);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('9177.8','H',24);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('7951.7','H',25);
INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES ('5042.5','H',26);


INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('10/10/2005',1);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('16/02/2010',2);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('16/02/2010',3);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('17/05/2004',4);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('17/05/2004',4);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('17/05/2004',5);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('11/11/2006',6);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('30/06/2007',6);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('5/5/2005',7);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('30/07/2007',7);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('2/4/2001',8);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('30/08/2007',9);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('13/02/2007',10);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('8/1/1999',11);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('30/06/2007',12);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('1/9/2008',13);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('1/9/2008',14);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('16/02/2010',15);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('27/03/2007',16);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('21/10/2009',17);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('6/1/2008',18);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('19/10/2008',19);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('4/11/2009',20);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('4/11/2009',21);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('29/05/2006',22);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('16/12/2008',23);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('23/12/2010',24);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('21/07/2007',25);
INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('4/6/2001',26);


INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('24778.6','H',1);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('24368.4','H',1);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('24582.6','H',1);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11827.8','H',2);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11827.8','H',3);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('26411','H',4);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('133462','L',5);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11211','H',5);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11571.3','H',6);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11951.7','H',6);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('10843.6','H',7);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11951.7','H',7);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11406','H',8);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('10351.7','H',9);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('12716.1','H',10);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('79976.26','H',11);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('9951.7','H',12);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11791.4','H',13);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('11791.4','H',14);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('10627.8','H',15);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('15-02-2016','D',15);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('9615.6','H',16);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('10554.2','H',17);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('10053.3','H',18);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('10176.1','H',19);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('9502.47','H',20);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('9502.47','H',21);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('12841.7','H',22);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('29-05-2016','D',22);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('12498.8','H',23);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('10777.8','H',24);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('25-09-2013','D',25);
INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('25042.5','H',26);


INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',1);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',2);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',3);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',4);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('19139','L',4);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',5);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',6);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',6);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',7);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',7);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',8);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',9);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',10);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',11);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',12);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',13);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',14);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',15);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('5/8/2011','D',15);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',16);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',17);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',18);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',19);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',20);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',21);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',22);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('5/8/2011','D',22);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',23);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',24);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('5/8/2011','D',25);
INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('9267.2','H',26);


INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '15511.4','H',1);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '15101.2','H',1);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '15315.4','H',1);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2591.5','H',2);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2560.6','H',3);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '17143.8','H',4);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '114323','L',4);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '1943.8','H',5);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2304.1','H',6);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2684.5','H',6);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '1576.4','H',7);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2684.5','H',7);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2138.8','H',8);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '1084.5','H',9);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '3448.9','H',10);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '70709.06','H',11);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '684.5','H',12);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2524.2','H',13);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '2524.2','H',14);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '1360.6','H',15);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '999','D',15);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '348.4','H',16);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '1287','H',17);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '786.1','H',18);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '908.9','H',19);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '235.27','H',20);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '235.27','D',21);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '3574.5','H',22);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '1759','D',22);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '3231.6','H',23);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '1510.6','H',24);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '75','D',25);
INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '15775.3','H',26);


INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',1);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',1);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',1);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'Life Increase IAW revised M. P. dt. 24.12.2007',2);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'Life Increase IAW revised M. P. dt. 24.12.2007',3);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',4);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In Landings',4);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',5);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',6);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',6);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',7);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',7);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',8);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'Life Increase IAW revised M. P. dt. 24.12.2007',9);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',10);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',11);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',12);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',13);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',14);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',15);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Days',15);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',16);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',17);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',18);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',19);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',20);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',21);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',22);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Days',22);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',23);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',24);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Days',25);
INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In  Hours',26);


--------------------------------------------------------------------------------------------------------------------------------
INSERT INTO airdyna.AIR_CRAFT (`AC_NAME`, `AC_SERIALNUM`, `AC_AFHRS`, `AC_ENGHRS`, `AC_LANDINGCOUNT`, `AC_STARTCOUNT`, `AC_ENGNGCYCS`, `AC_NPCYCS`, `AC_FORMNUM`) VALUES ('Eng-SN-921', '921', '9267.2', '7998.4', '19139', '10255', '11092.7', '10255.0', 'ADH 310 A');

INSERT INTO airdyna.COMPONENTS (`COMP_PARTNAME`, `COMP_PARTNUM`, `COMP_AC_ID`) VALUES ('MO1', '70BM 01 1080', 2);
	
INSERT INTO airdyna.CMP_SERIAL_NUMBER (`SERIALNUM_VALUE`, `SERIALNUM_COMP_ID`) VALUES ('1068', 2);

INSERT INTO airdyna.CMP_FINITELIFE (`CMP_FINITELIFE_HRS`,`CMP_FINITELIFE_HRS_TYPE`, `CMP_FINITELIFE_COMP_ID`) VALUES ('15','D', 2);

INSERT INTO airdyna.CMP_LIFEREM_INST (`CMPLIFE_REM_HRS`,`CMPLIFE_REM_HRS_TYPE`, `CMPLIFES_COMP_ID`) VALUES ('7022.60','H', 2);

INSERT INTO airdyna.CMP_AFHRS_INST (`CMP_AFHRS_INST_HRS`,`CMP_AFHRS_INST_HRS_TYPE`, `CMP_AFHRS_INST_COMP_ID`) VALUES('796.0','H', 2);

INSERT INTO airdyna.CMP_DATE_INST (`CMP_DATE_INST_DATE`, `CMP_DATE_INST_COMP_ID`) VALUES ('2008-09-02', 2);

INSERT INTO airdyna.COMP_DUEOFF_AFHRS_INST (`CDA_HRS`,`CDA_HRS_TYPE`, `CDA_COMP_ID`) VALUES ('2001-09-23','D', 2);

INSERT INTO airdyna.CMP_CUR_AFHRS (`CMP_CUR_AFHRS_HRS`,`CMP_CUR_AFHRS_HRS_TYPE`, `CMP_CUR_AFHRS_COMP_ID`) VALUES ('2011-08-05','D', 2);

INSERT INTO airdyna.COMP_REM_LIFE ( `CRL_HRS`,`CRL_HRS_TYPE`, `CRL_COMP_ID`) VALUES ( '4410','H', 2);

INSERT INTO airdyna.CMP_REMARKS ( `CMP_REMARKS_TEXT`, `CMP_REMARKS_COMP_ID`) VALUES ( 'In Days', 2);
--------------------------------------------------------------------------------------------------------------------------------
INSERT INTO airdyna.AF_ENG_INSP (`AES_NOMENCLATURE`, `AES_DUE_AF_HRS`, `AES_DUE_ENG_HRS`, `AES_CAL_DUE_DATE`, `AES_DUE_TIME`, `AES_REMARKS`, `AES_AC_ID`) VALUES ('A/F & Eng. - 100 Hrs.(Maintenance Release) ', '9323.90', '8055.10', '2011-09-14', '56.70', 'In Hours', 1);

INSERT INTO airdyna.OAF_CHANGE_INT (`OAFCI_NOMENCLATURE`, `OAFCI_SPECS`, `OAFCI_AC_ID`) VALUES ('Engine Oil', 'Jet Oil 254', 1);

INSERT INTO airdyna.OAFCI_INTERVAL (`OAFCINVL_HRS`, `OAFCINVL_HRS_TYPE`, `OAFCINVL_OAFCI_ID`) VALUES ('750', 'H', 1);
INSERT INTO airdyna.OAFCI_INTERVAL (`OAFCINVL_HRS`, `OAFCINVL_HRS_TYPE`, `OAFCINVL_OAFCI_ID`) VALUES ('2', 'Y', 1);

INSERT INTO airdyna.OAFCI_DUE_AT_HRS (`OANF_DAH_HRS`, `OANFDAH_HRS_TYPE`, `OANFDAH_OAFCI_ID`) VALUES ('8309.00', 'H', 1);
INSERT INTO airdyna.OAFCI_DUE_AT_HRS ( `OANF_DAH_HRS`, `OANFDAH_HRS_TYPE`, `OANFDAH_OAFCI_ID`) VALUES ('2012-02-16', 'D', 1);

INSERT INTO airdyna.OAFCI_DUE_HRS (`OAFDH_HRS`, `OAFDH_HRS_TYPE`, `OAFDH_OAFCI_ID`) VALUES ('310.60', 'H', 1);
INSERT INTO airdyna.OAFCI_DUE_HRS (`OAFDH_HRS`, `OAFDH_HRS_TYPE`, `OAFDH_OAFCI_ID`) VALUES ('2010-06-21', 'D', 1);

INSERT INTO airdyna.OAFCI_REMARKS (`OAFREM_TEXT`, `OAFREM_OAFCI_ID`) VALUES ('In Engine Hours', 1);
INSERT INTO airdyna.OAFCI_REMARKS (`OAFREM_TEXT`, `OAFREM_OAFCI_ID`) VALUES ('In Days', 1);
-------------------------------------------------------------------------------------------------------------------------------
INSERT INTO airdyna.OUT_PHASE_MNT (`OPM_NOMENCLATURE`, `OPM_DUE_AT`, `OPM_DUE_HRS`, `OPM_DUE_HRS_TYPE`, `OPM_CAL_DUE_DATE`, `OPM_AC_ID`) VALUES ('First Aid Kit', '', NULL, '', '2011-09-24', 1);

INSERT INTO airdyna.OPM_INTERVAL (`OPMINVL_HRS`, `OPMINVL_HRS_TYPE`, `OPMINVL_OPM_ID`) VALUES ('12', 'M', 1);
	
INSERT INTO airdyna.OPM_TIME_REM (`OPMTR_HRS`, `OPMTR_HRS_TYPE`, `OPMTR_OPM_ID`) VALUES ('365', 'D', 1);

INSERT INTO airdyna.OPM_REMARKS (`OPMREM_TEXT`, `OPMREM_OPM_ID`) VALUES ('In Days', 1);

--------------------------------------------------------------------------------------------------------------------------------
INSERT INTO airdyna.`USER` (`USER_NAME`, `USER_REALNAME`, `USER_PASSWORD`, `USER_EMAILID`) VALUES ('admin', 'admin', 'admin', 'admin@admin.com');

INSERT INTO airdyna.USER_GROUP (group_name, group_user_id) VALUES ('Administrator', 1);
INSERT INTO airdyna.USER_GROUP (group_name, group_user_id) VALUES ('User', 1);


--------------------------------------------------------------------------------------------------------------------------------

/afs1/SDK/bin/asadmin
login –-port 4848

undeploy --port 4848 xtg-war-01.06-00
deploy –-port 4848 xtg-war-01.06-01.war

stop-domain XTG_PRD
start-domain XTG_PRD






	
